tests: fetch2: npm-local-link-sources: add a test for npmsw fetcher with local link sources
* https://docs.npmjs.com/cli/v10/configuring-npm/package-lock-json
  shows 3 examples:

  http tarball sources: This is the URL of the tarball. (eg, https://example.com/example-1.3.0.tgz)
  local tarball sources: This is the file URL of the tarball. (eg file:///opt/storage/example-1.3.0.tgz)
  local link sources: This is the file URL of the link. (eg file:libs/our-module)

  it's not clear if the last one should start with file://, but in:
  https://git.openembedded.org/bitbake/commit/lib/bb/fetch2/npmsw.py?id=4f983dc419a1a6f635a5d333f253d49244cec374
  we strip 5 chars in:
  localpath = version[5:]
  so file:// wouldn't work in such case.

  It works well when parsing the dependency in:
    "@npm-local-link-sources/upper": "file:../"
  but then when parsing the npm-shrinkwrap.json package like:
    "..": {
      "name": "@local-link-sources/upper",
      "version": "1.0.0"
    },
    "node_modules/@local-link-sources/upper": {
      "resolved": "..",
      "link": true
    }

  it fails with:
  bb.data_smart.ExpansionError: Failure expanding variable fetcher_hashes_dummyfunc[vardepvalue], expression was ${@bb.fetch.get_hashvalue(d)} which triggered exception ParameterError: URL: 'npmsw://npm-shrinkwrap.json' has invalid parameters. Unsupported dependency: ..
  because it no longer has the "file:" prefix in the version to recognize local link.

  https://git.openembedded.org/bitbake/commit/lib/bb/fetch2/npmsw.py?id=19b9f7f0f451a636f3fdcdc1bb283ab431ede612
  switched to walk "packages" instead of "dependencies" to support
  lockfileVersion 2 (and 3) as in:

  No version provided: an "ancient" shrinkwrap file from a version of npm prior to npm v5.
  1: The lockfile version used by npm v5 and v6.
  2: The lockfile version used by npm v7 and v8. Backwards compatible to v1 lockfiles.
  3: The lockfile version used by npm v9 and above. Backwards compatible to npm v7.

  Add the npm source with npm-shrinkwrap files generated for all 3
  versions to better document the differences in this case and also
  easily compare what might change in some future npm with another
  lockfileVersion:
  npm-shrinkwrap-v1.json generated with npm-6.14.18
  npm-shrinkwrap-v2.json generated with npm-8.19.4
  npm-shrinkwrap-v3.json generated with npm-10.1.0

  There is only exception for "" package name used for root package
  and for all other packages it expects "node_modules/" prefix, which
  is stripped from the name

* I don't know how common this case is in npm ecosystem, but this is what
  we have in some component and what was failing with current npmsw://
  implementation, the SRC_URI is git repository with some libraries
  and a "sampler", S points to the "sampler" directory and npmsw:// uses
  the shrinkwrap file from this "sampler" which refers to the libraries
  to test in the directories above (so that it tests the libraries from
  the same checkout, not some other released version from npm registry)

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>