fetch2: npmsw: add few more information into ParameterError exception
* instead of:
  bb.fetch2.ParameterError: URL: 'npmsw:///tmp/bitbake-fetch-pqaqvbau/data/npm-shrinkwrap.json' has invalid parameters. Unsupported dependency: ..
  show:
  bb.fetch2.ParameterError: URL: 'npmsw:///tmp/bitbake-fetch-0h0bgkfn/data/npm-shrinkwrap.json' has invalid parameters. Unsupported dependency: name '..', depname '@npm-local-link-sources/upper', version '1.0.0', resolved 'None'

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>